name: Workify CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Set up Python 3.8.1
      uses: actions/setup-python@v3
      with:
        python-version: 3.8.1
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements